//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

import (
	common "k8s.io/kube-openapi/pkg/common"
	spec "k8s.io/kube-openapi/pkg/validation/spec"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicy":           schema_gke_networking_api_apis_fqdnnetworkpolicy_v1alpha1_FQDNNetworkPolicy(ref),
		"github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicyEgressRule": schema_gke_networking_api_apis_fqdnnetworkpolicy_v1alpha1_FQDNNetworkPolicyEgressRule(ref),
		"github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicyMatch":      schema_gke_networking_api_apis_fqdnnetworkpolicy_v1alpha1_FQDNNetworkPolicyMatch(ref),
		"github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicyPort":       schema_gke_networking_api_apis_fqdnnetworkpolicy_v1alpha1_FQDNNetworkPolicyPort(ref),
		"github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicySpec":       schema_gke_networking_api_apis_fqdnnetworkpolicy_v1alpha1_FQDNNetworkPolicySpec(ref),
	}
}

func schema_gke_networking_api_apis_fqdnnetworkpolicy_v1alpha1_FQDNNetworkPolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FQDNNetworkPolicy specifies which Fully-Qualified Domain Names a workload is allowed to egress to. FQDNNetworkPolicy has no effect on the allowed ingress traffic.\n\nFQDNNetworkPolicy works additively with Kubernetes Network Policies. Traffic matching either a Kubernetes NetworkPolicy or a FQDNNetworkPolicy will be allowed to egress the workload.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Description: "Spec is the desired configuration for FQDN Network Policy.",
							Default:     map[string]interface{}{},
							Ref:         ref("github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicySpec"),
						},
					},
				},
				Required: []string{"spec"},
			},
		},
		Dependencies: []string{
			"github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicySpec", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_gke_networking_api_apis_fqdnnetworkpolicy_v1alpha1_FQDNNetworkPolicyEgressRule(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FQDNNetworkPolicyEgressRule identifies a set of endpoints traffic is allowed to. The exact L4 endpoints are constructed as a cross-product between the matches and ports lists.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"matches": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "atomic",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "Matches specifies the FQDN peers to which egress traffic is allowed. Matches may not be missing or empty - it must contain at least 1 entry.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicyMatch"),
									},
								},
							},
						},
					},
					"ports": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "atomic",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "Ports specifies the destination L4 port and protocol allowed to egress the pod. If ports is missing or empty, all ports and protocols are allowed.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicyPort"),
									},
								},
							},
						},
					},
				},
				Required: []string{"matches"},
			},
		},
		Dependencies: []string{
			"github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicyMatch", "github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicyPort"},
	}
}

func schema_gke_networking_api_apis_fqdnnetworkpolicy_v1alpha1_FQDNNetworkPolicyMatch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FQDNNetworkPolicyMatch specifies which FQDNs are allowed as peers of the selected pods.Exactly one of the sub-fields of FQDNNetworkPolicyMatch must be set. An empty struct is not allowed. A struct setting both Name and Pattern is not allowed.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Description: "Name specifies the literal FQDN to match. If this is specified, no other match types may be specified in the same struct.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"pattern": {
						SchemaProps: spec.SchemaProps{
							Description: "Pattern allows matching FQDNs using wildcard specifiers. If this is specified, no other match types may be specified in the same struct. \"*\" matches 0 or more DNS valid characters (except for \".\"), and may occur anywhere in the pattern. As a special case, the \"*\" character by itself acts as a wildcard, matching all domain names.\n\nExamples:\n\n  - `*.google.com` matches subdomains of google.com at that level\n    - \"www.google.com\" and \"mail.google.com\" match, however \"google.com\",\n      \"sub.subdomain.google.com\", and \"kubernetes.io\" do not.\n  - `sub*.google.com` matches subdomains of google.com where the subdomain\n    component begins with \"sub\"\n    - \"sub.google.com\" and \"subdomain.google.com\" match, however\n      \"www.google.com\", \"mail.google.com\", and \"google.com do not.\n  - `*.*.google.com` matches subdomains of google.com at that level\n    - \"sub.subdomain.google.com\" matches, however \"google.com\" and\n      \"mail.google.com\" do not.\n  - `*a*.google.com` matches subdomains of google.com that contain an \"a\" at\n    that level\n    - \"mail.google.com\", \"maps.google.com\", and\n      \"subdomain.maps.google.com\" match, however \"google.com\" and\n      \"cloud.google.com\" do not.\n  - `*` by itself is a wild-card that matches all domains\n    - \"www.google.com\", \"kubernetes.io\", and \"sub.subdomain.google.com\"\n      all match",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
	}
}

func schema_gke_networking_api_apis_fqdnnetworkpolicy_v1alpha1_FQDNNetworkPolicyPort(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FQDNNetworkPolicyPort specifies which remote port and protocol is a valid peer of the selected pod.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"protocol": {
						SchemaProps: spec.SchemaProps{
							Description: "Protocol is the L4 protocol. Valid options are \"TCP\", \"UDP\", or \"ALL\". If Protocol is missing or empty, it defaults to allowing all protocols.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"port": {
						SchemaProps: spec.SchemaProps{
							Description: "Port is L4 Port. If Port is missing or empty, it matches all ports.",
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
				},
			},
		},
	}
}

func schema_gke_networking_api_apis_fqdnnetworkpolicy_v1alpha1_FQDNNetworkPolicySpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"podSelector": {
						SchemaProps: spec.SchemaProps{
							Description: "PodSelector defines which workloads are selected by the Policy. An empty PodSelector selects all pods in the namespace.",
							Default:     map[string]interface{}{},
							Ref:         ref("k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelector"),
						},
					},
					"egress": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "atomic",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "Egress specifies a list of rules applied to the selected pods. All egress rules are enforced using an implicit deny model (like Kubernetes Network Policies) -- only packets destined for IPs resolving the matching FQDNs and ports are allowed.\n\nEgress may not be missing or empty - it must contain at least 1 entry.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicyEgressRule"),
									},
								},
							},
						},
					},
				},
				Required: []string{"podSelector", "egress"},
			},
		},
		Dependencies: []string{
			"github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1.FQDNNetworkPolicyEgressRule", "k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelector"},
	}
}
