//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by openapi-gen. DO NOT EDIT.

package v1

import (
	common "k8s.io/kube-openapi/pkg/common"
	spec "k8s.io/kube-openapi/pkg/validation/spec"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/GoogleCloudPlatform/gke-networking-api/apis/nodetopology/v1.NodeTopologyStatus": schema_gke_networking_api_apis_nodetopology_v1_NodeTopologyStatus(ref),
	}
}

func schema_gke_networking_api_apis_nodetopology_v1_NodeTopologyStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NodeTopologyStatus is the status for a NodeTopology resource",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"zones": {
						SchemaProps: spec.SchemaProps{
							Description: "Zones specifies the current node zones of the GKE cluster that corresponds to this NodeTopology Resource.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
					"subnets": {
						SchemaProps: spec.SchemaProps{
							Description: "Subnets contains the list of subnets used by the GKE cluster that corresponds to this Node Topology Resource.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/GoogleCloudPlatform/gke-networking-api/apis/nodetopology/v1.SubnetConfig"),
									},
								},
							},
						},
					},
					"conditions": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-map-keys": []interface{}{
									"type",
								},
								"x-kubernetes-list-type": "map",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "Conditions contains the latest conditions observed of this Node Tolology resource.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/GoogleCloudPlatform/gke-networking-api/apis/nodetopology/v1.Condition"),
									},
								},
							},
						},
					},
				},
				Required: []string{"zones", "subnets"},
			},
		},
		Dependencies: []string{
			"github.com/GoogleCloudPlatform/gke-networking-api/apis/nodetopology/v1.Condition", "github.com/GoogleCloudPlatform/gke-networking-api/apis/nodetopology/v1.SubnetConfig"},
	}
}
