//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by openapi-gen. DO NOT EDIT.

package v1

import (
	common "k8s.io/kube-openapi/pkg/common"
	spec "k8s.io/kube-openapi/pkg/validation/spec"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1.DependantResources":       schema_gke_networking_api_apis_dependantresources_v1_DependantResources(ref),
		"github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1.DependantResourcesList":   schema_gke_networking_api_apis_dependantresources_v1_DependantResourcesList(ref),
		"github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1.DependantResourcesSpec":   schema_gke_networking_api_apis_dependantresources_v1_DependantResourcesSpec(ref),
		"github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1.DependantResourcesStatus": schema_gke_networking_api_apis_dependantresources_v1_DependantResourcesStatus(ref),
	}
}

func schema_gke_networking_api_apis_dependantresources_v1_DependantResources(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DependantResources holds the mapping between a GKE Service and the GCE resources it configures.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Description: "Spec defines the desired state of DependantResources. This field is currently unused.",
							Default:     map[string]interface{}{},
							Ref:         ref("github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1.DependantResourcesSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Description: "Status defines the observed state of DependantResources. This field is populated by the controller with the list of GCE resources.",
							Default:     map[string]interface{}{},
							Ref:         ref("github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1.DependantResourcesStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1.DependantResourcesSpec", "github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1.DependantResourcesStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_gke_networking_api_apis_dependantresources_v1_DependantResourcesList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DependantResourcesList contains a list of DependantResources.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta"),
						},
					},
					"items": {
						SchemaProps: spec.SchemaProps{
							Description: "Items is the list of DependantResources.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1.DependantResources"),
									},
								},
							},
						},
					},
				},
				Required: []string{"items"},
			},
		},
		Dependencies: []string{
			"github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1.DependantResources", "k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta"},
	}
}

func schema_gke_networking_api_apis_dependantresources_v1_DependantResourcesSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DependantResourcesSpec is the spec for a DependantResources resource",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_gke_networking_api_apis_dependantresources_v1_DependantResourcesStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DependantResourcesStatus defines the observed state of DependantResources.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"resources": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "set",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "Resources is a list of URLs for resources provisioned by the controller for the referenced object. This field is managed exclusively by the controller.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: "",
										Type:    []string{"string"},
										Format:  "",
									},
								},
							},
						},
					},
				},
			},
		},
	}
}
