/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1"
	scheme "github.com/GoogleCloudPlatform/gke-networking-api/client/dependantresources/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DependantResourcesesGetter has a method to return a DependantResourcesInterface.
// A group's client should implement this interface.
type DependantResourcesesGetter interface {
	DependantResourceses(namespace string) DependantResourcesInterface
}

// DependantResourcesInterface has methods to work with DependantResources resources.
type DependantResourcesInterface interface {
	Create(ctx context.Context, dependantResources *v1.DependantResources, opts metav1.CreateOptions) (*v1.DependantResources, error)
	Update(ctx context.Context, dependantResources *v1.DependantResources, opts metav1.UpdateOptions) (*v1.DependantResources, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, dependantResources *v1.DependantResources, opts metav1.UpdateOptions) (*v1.DependantResources, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DependantResources, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DependantResourcesList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DependantResources, err error)
	DependantResourcesExpansion
}

// dependantResourceses implements DependantResourcesInterface
type dependantResourceses struct {
	*gentype.ClientWithList[*v1.DependantResources, *v1.DependantResourcesList]
}

// newDependantResourceses returns a DependantResourceses
func newDependantResourceses(c *NetworkingV1Client, namespace string) *dependantResourceses {
	return &dependantResourceses{
		gentype.NewClientWithList[*v1.DependantResources, *v1.DependantResourcesList](
			"dependantresourceses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.DependantResources { return &v1.DependantResources{} },
			func() *v1.DependantResourcesList { return &v1.DependantResourcesList{} }),
	}
}
