/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// DependantResourcesLister helps list DependantResourceses.
// All objects returned here must be treated as read-only.
type DependantResourcesLister interface {
	// List lists all DependantResourceses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DependantResources, err error)
	// DependantResourceses returns an object that can list and get DependantResourceses.
	DependantResourceses(namespace string) DependantResourcesNamespaceLister
	DependantResourcesListerExpansion
}

// dependantResourcesLister implements the DependantResourcesLister interface.
type dependantResourcesLister struct {
	listers.ResourceIndexer[*v1.DependantResources]
}

// NewDependantResourcesLister returns a new DependantResourcesLister.
func NewDependantResourcesLister(indexer cache.Indexer) DependantResourcesLister {
	return &dependantResourcesLister{listers.New[*v1.DependantResources](indexer, v1.Resource("dependantresources"))}
}

// DependantResourceses returns an object that can list and get DependantResourceses.
func (s *dependantResourcesLister) DependantResourceses(namespace string) DependantResourcesNamespaceLister {
	return dependantResourcesNamespaceLister{listers.NewNamespaced[*v1.DependantResources](s.ResourceIndexer, namespace)}
}

// DependantResourcesNamespaceLister helps list and get DependantResourceses.
// All objects returned here must be treated as read-only.
type DependantResourcesNamespaceLister interface {
	// List lists all DependantResourceses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DependantResources, err error)
	// Get retrieves the DependantResources from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.DependantResources, error)
	DependantResourcesNamespaceListerExpansion
}

// dependantResourcesNamespaceLister implements the DependantResourcesNamespaceLister
// interface.
type dependantResourcesNamespaceLister struct {
	listers.ResourceIndexer[*v1.DependantResources]
}
