/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFQDNNetworkPolicies implements FQDNNetworkPolicyInterface
type FakeFQDNNetworkPolicies struct {
	Fake *FakeNetworkingV1alpha1
	ns   string
}

var fqdnnetworkpoliciesResource = v1alpha1.SchemeGroupVersion.WithResource("fqdnnetworkpolicies")

var fqdnnetworkpoliciesKind = v1alpha1.SchemeGroupVersion.WithKind("FQDNNetworkPolicy")

// Get takes name of the fQDNNetworkPolicy, and returns the corresponding fQDNNetworkPolicy object, and an error if there is any.
func (c *FakeFQDNNetworkPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FQDNNetworkPolicy, err error) {
	emptyResult := &v1alpha1.FQDNNetworkPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(fqdnnetworkpoliciesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.FQDNNetworkPolicy), err
}

// List takes label and field selectors, and returns the list of FQDNNetworkPolicies that match those selectors.
func (c *FakeFQDNNetworkPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FQDNNetworkPolicyList, err error) {
	emptyResult := &v1alpha1.FQDNNetworkPolicyList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(fqdnnetworkpoliciesResource, fqdnnetworkpoliciesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FQDNNetworkPolicyList{ListMeta: obj.(*v1alpha1.FQDNNetworkPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.FQDNNetworkPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fQDNNetworkPolicies.
func (c *FakeFQDNNetworkPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(fqdnnetworkpoliciesResource, c.ns, opts))

}

// Create takes the representation of a fQDNNetworkPolicy and creates it.  Returns the server's representation of the fQDNNetworkPolicy, and an error, if there is any.
func (c *FakeFQDNNetworkPolicies) Create(ctx context.Context, fQDNNetworkPolicy *v1alpha1.FQDNNetworkPolicy, opts v1.CreateOptions) (result *v1alpha1.FQDNNetworkPolicy, err error) {
	emptyResult := &v1alpha1.FQDNNetworkPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(fqdnnetworkpoliciesResource, c.ns, fQDNNetworkPolicy, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.FQDNNetworkPolicy), err
}

// Update takes the representation of a fQDNNetworkPolicy and updates it. Returns the server's representation of the fQDNNetworkPolicy, and an error, if there is any.
func (c *FakeFQDNNetworkPolicies) Update(ctx context.Context, fQDNNetworkPolicy *v1alpha1.FQDNNetworkPolicy, opts v1.UpdateOptions) (result *v1alpha1.FQDNNetworkPolicy, err error) {
	emptyResult := &v1alpha1.FQDNNetworkPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(fqdnnetworkpoliciesResource, c.ns, fQDNNetworkPolicy, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.FQDNNetworkPolicy), err
}

// Delete takes name of the fQDNNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *FakeFQDNNetworkPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(fqdnnetworkpoliciesResource, c.ns, name, opts), &v1alpha1.FQDNNetworkPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFQDNNetworkPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(fqdnnetworkpoliciesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FQDNNetworkPolicyList{})
	return err
}

// Patch applies the patch and returns the patched fQDNNetworkPolicy.
func (c *FakeFQDNNetworkPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FQDNNetworkPolicy, err error) {
	emptyResult := &v1alpha1.FQDNNetworkPolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(fqdnnetworkpoliciesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.FQDNNetworkPolicy), err
}
