/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1"
	fqdnnetworkpolicyv1alpha1 "github.com/GoogleCloudPlatform/gke-networking-api/client/fqdnnetworkpolicy/clientset/versioned/typed/fqdnnetworkpolicy/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeFQDNNetworkPolicies implements FQDNNetworkPolicyInterface
type fakeFQDNNetworkPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.FQDNNetworkPolicy, *v1alpha1.FQDNNetworkPolicyList]
	Fake *FakeNetworkingV1alpha1
}

func newFakeFQDNNetworkPolicies(fake *FakeNetworkingV1alpha1, namespace string) fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicyInterface {
	return &fakeFQDNNetworkPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.FQDNNetworkPolicy, *v1alpha1.FQDNNetworkPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("fqdnnetworkpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("FQDNNetworkPolicy"),
			func() *v1alpha1.FQDNNetworkPolicy { return &v1alpha1.FQDNNetworkPolicy{} },
			func() *v1alpha1.FQDNNetworkPolicyList { return &v1alpha1.FQDNNetworkPolicyList{} },
			func(dst, src *v1alpha1.FQDNNetworkPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.FQDNNetworkPolicyList) []*v1alpha1.FQDNNetworkPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.FQDNNetworkPolicyList, items []*v1alpha1.FQDNNetworkPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
