/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	fqdnnetworkpolicyv1alpha1 "github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1"
	scheme "github.com/GoogleCloudPlatform/gke-networking-api/client/fqdnnetworkpolicy/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FQDNNetworkPoliciesGetter has a method to return a FQDNNetworkPolicyInterface.
// A group's client should implement this interface.
type FQDNNetworkPoliciesGetter interface {
	FQDNNetworkPolicies(namespace string) FQDNNetworkPolicyInterface
}

// FQDNNetworkPolicyInterface has methods to work with FQDNNetworkPolicy resources.
type FQDNNetworkPolicyInterface interface {
	Create(ctx context.Context, fQDNNetworkPolicy *fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy, opts v1.CreateOptions) (*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy, error)
	Update(ctx context.Context, fQDNNetworkPolicy *fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy, opts v1.UpdateOptions) (*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy, err error)
	FQDNNetworkPolicyExpansion
}

// fQDNNetworkPolicies implements FQDNNetworkPolicyInterface
type fQDNNetworkPolicies struct {
	*gentype.ClientWithList[*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy, *fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicyList]
}

// newFQDNNetworkPolicies returns a FQDNNetworkPolicies
func newFQDNNetworkPolicies(c *NetworkingV1alpha1Client, namespace string) *fQDNNetworkPolicies {
	return &fQDNNetworkPolicies{
		gentype.NewClientWithList[*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy, *fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicyList](
			"fqdnnetworkpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy {
				return &fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy{}
			},
			func() *fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicyList {
				return &fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicyList{}
			},
		),
	}
}
