/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1"
	scheme "github.com/GoogleCloudPlatform/gke-networking-api/client/fqdnnetworkpolicy/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// FQDNNetworkPolicyListsGetter has a method to return a FQDNNetworkPolicyListInterface.
// A group's client should implement this interface.
type FQDNNetworkPolicyListsGetter interface {
	FQDNNetworkPolicyLists(namespace string) FQDNNetworkPolicyListInterface
}

// FQDNNetworkPolicyListInterface has methods to work with FQDNNetworkPolicyList resources.
type FQDNNetworkPolicyListInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FQDNNetworkPolicyList, error)
	FQDNNetworkPolicyListExpansion
}

// fQDNNetworkPolicyLists implements FQDNNetworkPolicyListInterface
type fQDNNetworkPolicyLists struct {
	*gentype.Client[*v1alpha1.FQDNNetworkPolicyList]
}

// newFQDNNetworkPolicyLists returns a FQDNNetworkPolicyLists
func newFQDNNetworkPolicyLists(c *NetworkingV1alpha1Client, namespace string) *fQDNNetworkPolicyLists {
	return &fQDNNetworkPolicyLists{
		gentype.NewClient[*v1alpha1.FQDNNetworkPolicyList](
			"fqdnnetworkpolicylists",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.FQDNNetworkPolicyList { return &v1alpha1.FQDNNetworkPolicyList{} }),
	}
}
