/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	dependantresourcesv1 "github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1"
	versioned "github.com/GoogleCloudPlatform/gke-networking-api/client/dependantresources/clientset/versioned"
	internalinterfaces "github.com/GoogleCloudPlatform/gke-networking-api/client/dependantresources/informers/externalversions/internalinterfaces"
	v1 "github.com/GoogleCloudPlatform/gke-networking-api/client/dependantresources/listers/dependantresources/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DependantResourcesInformer provides access to a shared informer and lister for
// DependantResourceses.
type DependantResourcesInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DependantResourcesLister
}

type dependantResourcesInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDependantResourcesInformer constructs a new informer for DependantResources type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDependantResourcesInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDependantResourcesInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDependantResourcesInformer constructs a new informer for DependantResources type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDependantResourcesInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1().DependantResourceses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1().DependantResourceses(namespace).Watch(context.TODO(), options)
			},
		},
		&dependantresourcesv1.DependantResources{},
		resyncPeriod,
		indexers,
	)
}

func (f *dependantResourcesInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDependantResourcesInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dependantResourcesInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dependantresourcesv1.DependantResources{}, f.defaultInformer)
}

func (f *dependantResourcesInformer) Lister() v1.DependantResourcesLister {
	return v1.NewDependantResourcesLister(f.Informer().GetIndexer())
}
