/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/GoogleCloudPlatform/gke-networking-api/apis/dependantresources/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDependantResourceses implements DependantResourcesInterface
type FakeDependantResourceses struct {
	Fake *FakeNetworkingV1
	ns   string
}

var dependantresourcesesResource = v1.SchemeGroupVersion.WithResource("dependantresourceses")

var dependantresourcesesKind = v1.SchemeGroupVersion.WithKind("DependantResources")

// Get takes name of the dependantResources, and returns the corresponding dependantResources object, and an error if there is any.
func (c *FakeDependantResourceses) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DependantResources, err error) {
	emptyResult := &v1.DependantResources{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(dependantresourcesesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.DependantResources), err
}

// List takes label and field selectors, and returns the list of DependantResourceses that match those selectors.
func (c *FakeDependantResourceses) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DependantResourcesList, err error) {
	emptyResult := &v1.DependantResourcesList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(dependantresourcesesResource, dependantresourcesesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.DependantResourcesList{ListMeta: obj.(*v1.DependantResourcesList).ListMeta}
	for _, item := range obj.(*v1.DependantResourcesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dependantResourceses.
func (c *FakeDependantResourceses) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(dependantresourcesesResource, c.ns, opts))

}

// Create takes the representation of a dependantResources and creates it.  Returns the server's representation of the dependantResources, and an error, if there is any.
func (c *FakeDependantResourceses) Create(ctx context.Context, dependantResources *v1.DependantResources, opts metav1.CreateOptions) (result *v1.DependantResources, err error) {
	emptyResult := &v1.DependantResources{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(dependantresourcesesResource, c.ns, dependantResources, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.DependantResources), err
}

// Update takes the representation of a dependantResources and updates it. Returns the server's representation of the dependantResources, and an error, if there is any.
func (c *FakeDependantResourceses) Update(ctx context.Context, dependantResources *v1.DependantResources, opts metav1.UpdateOptions) (result *v1.DependantResources, err error) {
	emptyResult := &v1.DependantResources{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(dependantresourcesesResource, c.ns, dependantResources, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.DependantResources), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDependantResourceses) UpdateStatus(ctx context.Context, dependantResources *v1.DependantResources, opts metav1.UpdateOptions) (result *v1.DependantResources, err error) {
	emptyResult := &v1.DependantResources{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(dependantresourcesesResource, "status", c.ns, dependantResources, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.DependantResources), err
}

// Delete takes name of the dependantResources and deletes it. Returns an error if one occurs.
func (c *FakeDependantResourceses) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dependantresourcesesResource, c.ns, name, opts), &v1.DependantResources{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDependantResourceses) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(dependantresourcesesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.DependantResourcesList{})
	return err
}

// Patch applies the patch and returns the patched dependantResources.
func (c *FakeDependantResourceses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DependantResources, err error) {
	emptyResult := &v1.DependantResources{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(dependantresourcesesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.DependantResources), err
}
