/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	fqdnnetworkpolicyv1alpha1 "github.com/GoogleCloudPlatform/gke-networking-api/apis/fqdnnetworkpolicy/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// FQDNNetworkPolicyLister helps list FQDNNetworkPolicies.
// All objects returned here must be treated as read-only.
type FQDNNetworkPolicyLister interface {
	// List lists all FQDNNetworkPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy, err error)
	// FQDNNetworkPolicies returns an object that can list and get FQDNNetworkPolicies.
	FQDNNetworkPolicies(namespace string) FQDNNetworkPolicyNamespaceLister
	FQDNNetworkPolicyListerExpansion
}

// fQDNNetworkPolicyLister implements the FQDNNetworkPolicyLister interface.
type fQDNNetworkPolicyLister struct {
	listers.ResourceIndexer[*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy]
}

// NewFQDNNetworkPolicyLister returns a new FQDNNetworkPolicyLister.
func NewFQDNNetworkPolicyLister(indexer cache.Indexer) FQDNNetworkPolicyLister {
	return &fQDNNetworkPolicyLister{listers.New[*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy](indexer, fqdnnetworkpolicyv1alpha1.Resource("fqdnnetworkpolicy"))}
}

// FQDNNetworkPolicies returns an object that can list and get FQDNNetworkPolicies.
func (s *fQDNNetworkPolicyLister) FQDNNetworkPolicies(namespace string) FQDNNetworkPolicyNamespaceLister {
	return fQDNNetworkPolicyNamespaceLister{listers.NewNamespaced[*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy](s.ResourceIndexer, namespace)}
}

// FQDNNetworkPolicyNamespaceLister helps list and get FQDNNetworkPolicies.
// All objects returned here must be treated as read-only.
type FQDNNetworkPolicyNamespaceLister interface {
	// List lists all FQDNNetworkPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy, err error)
	// Get retrieves the FQDNNetworkPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy, error)
	FQDNNetworkPolicyNamespaceListerExpansion
}

// fQDNNetworkPolicyNamespaceLister implements the FQDNNetworkPolicyNamespaceLister
// interface.
type fQDNNetworkPolicyNamespaceLister struct {
	listers.ResourceIndexer[*fqdnnetworkpolicyv1alpha1.FQDNNetworkPolicy]
}
