/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/GoogleCloudPlatform/gke-networking-api/apis/serviceloadbalancerstatus/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServiceLoadBalancerStatuses implements ServiceLoadBalancerStatusInterface
type FakeServiceLoadBalancerStatuses struct {
	Fake *FakeNetworkingV1
	ns   string
}

var serviceloadbalancerstatusesResource = v1.SchemeGroupVersion.WithResource("serviceloadbalancerstatuses")

var serviceloadbalancerstatusesKind = v1.SchemeGroupVersion.WithKind("ServiceLoadBalancerStatus")

// Get takes name of the serviceLoadBalancerStatus, and returns the corresponding serviceLoadBalancerStatus object, and an error if there is any.
func (c *FakeServiceLoadBalancerStatuses) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ServiceLoadBalancerStatus, err error) {
	emptyResult := &v1.ServiceLoadBalancerStatus{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(serviceloadbalancerstatusesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.ServiceLoadBalancerStatus), err
}

// List takes label and field selectors, and returns the list of ServiceLoadBalancerStatuses that match those selectors.
func (c *FakeServiceLoadBalancerStatuses) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ServiceLoadBalancerStatusList, err error) {
	emptyResult := &v1.ServiceLoadBalancerStatusList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(serviceloadbalancerstatusesResource, serviceloadbalancerstatusesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ServiceLoadBalancerStatusList{ListMeta: obj.(*v1.ServiceLoadBalancerStatusList).ListMeta}
	for _, item := range obj.(*v1.ServiceLoadBalancerStatusList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceLoadBalancerStatuses.
func (c *FakeServiceLoadBalancerStatuses) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(serviceloadbalancerstatusesResource, c.ns, opts))

}

// Create takes the representation of a serviceLoadBalancerStatus and creates it.  Returns the server's representation of the serviceLoadBalancerStatus, and an error, if there is any.
func (c *FakeServiceLoadBalancerStatuses) Create(ctx context.Context, serviceLoadBalancerStatus *v1.ServiceLoadBalancerStatus, opts metav1.CreateOptions) (result *v1.ServiceLoadBalancerStatus, err error) {
	emptyResult := &v1.ServiceLoadBalancerStatus{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(serviceloadbalancerstatusesResource, c.ns, serviceLoadBalancerStatus, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.ServiceLoadBalancerStatus), err
}

// Update takes the representation of a serviceLoadBalancerStatus and updates it. Returns the server's representation of the serviceLoadBalancerStatus, and an error, if there is any.
func (c *FakeServiceLoadBalancerStatuses) Update(ctx context.Context, serviceLoadBalancerStatus *v1.ServiceLoadBalancerStatus, opts metav1.UpdateOptions) (result *v1.ServiceLoadBalancerStatus, err error) {
	emptyResult := &v1.ServiceLoadBalancerStatus{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(serviceloadbalancerstatusesResource, c.ns, serviceLoadBalancerStatus, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.ServiceLoadBalancerStatus), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServiceLoadBalancerStatuses) UpdateStatus(ctx context.Context, serviceLoadBalancerStatus *v1.ServiceLoadBalancerStatus, opts metav1.UpdateOptions) (result *v1.ServiceLoadBalancerStatus, err error) {
	emptyResult := &v1.ServiceLoadBalancerStatus{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(serviceloadbalancerstatusesResource, "status", c.ns, serviceLoadBalancerStatus, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.ServiceLoadBalancerStatus), err
}

// Delete takes name of the serviceLoadBalancerStatus and deletes it. Returns an error if one occurs.
func (c *FakeServiceLoadBalancerStatuses) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(serviceloadbalancerstatusesResource, c.ns, name, opts), &v1.ServiceLoadBalancerStatus{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceLoadBalancerStatuses) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(serviceloadbalancerstatusesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ServiceLoadBalancerStatusList{})
	return err
}

// Patch applies the patch and returns the patched serviceLoadBalancerStatus.
func (c *FakeServiceLoadBalancerStatuses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ServiceLoadBalancerStatus, err error) {
	emptyResult := &v1.ServiceLoadBalancerStatus{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(serviceloadbalancerstatusesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.ServiceLoadBalancerStatus), err
}
