# This workflow verifies that the generated files are in sync with API types.
name: Verify Codegen
on:  [ push, pull_request ]
jobs:
  run-verify-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        id: checkout

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Run the verify script
        run: |
          ./hack/verify-codegen.sh
        id: verify
